# Generated by Django 2.2.5 on 2021-06-02 08:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Marketing_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_Name', models.CharField(max_length=255)),
                ('customer_Number', models.CharField(max_length=255)),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('customer_Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.Loc')),
                ('customer_Source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.source')),
            ],
        ),
    ]
